### ISSUE TITLE
これ以外の連絡手段がなかったため

### ISSUE THREAD

**Issue by ghost** [YuaHyodo/ShogiAI_Book#1]
まず弁明からさせてもらうと携帯壊しました。
あとdiscordも移転したので(ID覚えとけば良かったね(それどころの話じゃねえよ))
近所のプログラマーが君位しかいないので
またかかわってくれるならここ(にとり#3618)に１１０番
discord移転多いのは僕が気まぐれだからですねすみませんでした

**Comment by YuaHyodo** [comment]
ああ、久しぶり。(何ヵ月ぶりだっけ)

今、そのアカウントにフレンド申請を送ってみたよ。(僕のアカウントは前と同じ)
申請が来てなかったら教えてくれ。

こんなオープンなところで話をするのもあれだし、続きはDiscordでよろしく。

**Comment by ghost** [comment]
近いうちにテレグラムのアカウントを作るのでお話したいです😣
